### ISSUE TITLE
Hi how to use it? 

### ISSUE THREAD

**Issue by hwongcom** [AntonioCS/mustache#1]
I have included in "mustache.h"

I did make. But doesn'T work? How to get it to work?

**Comment by AntonioCS** [comment]
Hey hwongcom. I have been changing the code a bit but it should still work. This, for now, is not a library so you still have to compile with your project.
Include the .h file and pass the .c file when you are compiling your project.

In these coming weeks I do plan to add some missing functionality and change the make file to create a library so it can be linked.

Hope this helps.

**Comment by hwongcom** [comment]
Include the .h file and pass the .c file when you are compiling your project.?

what do you mean by pass the .c file? i don't know how to pass the .c... sorry i'm newbie in C language

can you provide an example? what you do after you unzip the master, what next?

you have a lot of files inside and i cant make sense of it.

i tried the example but it says main.c missing in mustache

i thought the program only have one main... so i'm not sure where to put the main.c

**Comment by hwongcom** [comment]
As it is, i have tried but src/main.c: undefined symbol: mustache_init

doesn't seem to work out of the box or user friendly.

**Comment by AntonioCS** [comment]
You are right, it is not. I will try to improve it. 
But please view the tests/tests.c file. It does show how to use the current version.

Stability will improve in the future

**Comment by hwongcom** [comment]
great! thanks. great work by the way, i like your c template compared with others on github. it shows the most promising potential for c users.

pls do try to get the example working as a library. thanks
